from __future__ import annotations

from typing import Protocol

from ..domain.entities import ListingAggregate, TaskAggregate


class ListingRepository(Protocol):
    def get_by_key(self, product_id: int, account_id: int, market_code: str) -> ListingAggregate | None: ...
    def save(self, listing: ListingAggregate) -> ListingAggregate: ...


class TaskRepository(Protocol):
    def save(self, task: TaskAggregate) -> TaskAggregate: ...


class UnitOfWork(Protocol):
    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
